trigger: 
- main

pool: 
   name: SWF_Burgos_Spain_env

jobs:
- deployment: VMDeploy
  displayName: Deploy to VM
  environment: 
   name: dev
   resourceType: VirtualMachine
  strategy:
     runOnce:
        deploy:   
          steps:
            - script: echo "Hello world"
            - script: hostname
            - powershell: |
               Write-Host "Hello World"
               $last_tag = & 'git' 'describe' '--tags' '--abbrev=0'
               Write-Host "Version is $($last_tag)"

               ##################################################

               Set-Variable -Name "mytag" -Value "$last_tag"
               Get-Variable -Name "mytag"
              displayName: 'Git Tags'
