trigger: 
- main

pool: 
   name: SWF_Burgos_Spain_env

jobs:
- deployment: VMDeploy
  displayName: Deploy to VM
  environment: 
   name: dev
   resourceType: VirtualMachine
  strategy:
     runOnce:
        deploy:   
          steps:
            - script: echo "Hello world"
            - script: hostname
