variables:
- name: BuildParameters.solution
  value: '**\*.sln'
- name: BuildParameters.ArtifactName
  value: drop
  
trigger: 
- main

pool: 
   name: SWF_Burgos_Spain_env

jobs:
- deployment: VMDeploy
  displayName: Deploy to VM
  environment: 
   name: dev
   resourceType: VirtualMachine
  strategy:
     runOnce:
        deploy:   
          steps:
            - script: echo "Hello world"
            - script: hostname
            - task: NuGetToolInstaller@0
              displayName: 'Use NuGet 4.4.1'
              inputs:
                versionSpec: 4.4.1

            - task: NuGetCommand@2
              displayName: 'NuGet restore'
              inputs:
                restoreSolution: '$(Parameters.solution)'
  
