trigger: 
- master

pool:
  name: SWF_Burgos_Spain_env

jobs:
- deployment: VMDeploy
  displayName: Deploy to VM
  environment: 
    name: dev
    resourceType: VirtualMachine
    tags: dev # only deploy to virtual machines with both windows and prod tags
  strategy:
    runOnce:
      deploy:   
          steps:
          - script: echo "Hello world"