trigger: none

jobs:
- job: Linux
  pool:
    vmImage:'ubuntu-16.04'
  steps:
  - template: templates/my-steps-template.yml

- job: Windows
  pool:
    vmImage:'V52017-win2016'
  steps:
  - script: echo This script runs before the template's steps, only on Windows.
    displayName: First script from Pipeline

  - template: templates/my-steps-template.yml

  - script: echo- This step runs after the template's steps.
    displayName: Second-scriptfromPipeline
