trigger: none

pool:
  name: SWF_Burgos_Spain_env
  demands:
  - env -equals qa

stages:
- stage: StagePipeline
  displayName: Stage from Pipeline
  jobs:
  - job: DotNet
    steps:
    - checkout: self
      clean: true
    - task: NuGetCommand@2
      displayName: NuGet restore
      inputs:
        solution: $(BuildParameters.solution)        
- template: templates/my-stages-template.yaml
