jobs:
  - job: Ubuntu
    pool:
      name: SWF_Burgos_Spain_env
      demands:
      - env -equals qa      
    steps:
    - script: echo Hello Ubuntu
      displayName: Script from Template
    
  - job: Windows
    pool:
      name: SWF_Burgos_Spain_env
      demands:
      - env -equals qa2  
    steps:
    - script: echo Hello Windows
      displayName: Script from Template
