jobs:
  - job: Ubuntu
    pool:
      name: SWF_Burgos_Spain_env
      demands:
      - env -equals qa      
    steps:
    - bash: echo "Hello Ubuntu"
    
  - job: Windows
    pool:
      vmImage: 'windows-latest'
    steps:
    - bash: echo "Hello Windows"
