stages:
- stage: StageTemplate
  displayName: Stage from Template
  jobs:
  - job: DotNet
    steps:
    - checkout: self
      clean: true
    - task: UseDotNet@2
      displayName: Use .NET Core sdk 2.2.207
      inputs:
        version: 2.2.207      