name: Create Tag

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # - uses: butlerlogic/action-autotag@stable
    #   with:
    #     GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    #     strategy: package
    #    # root: "/path/to/subdirectory"
    - uses: ButlerLogic/action-autotag@1.1.1
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        strategy: regex # Optional since regex_pattern is defined
        root: "src/my.file"
        regex_pattern: "(version=)(?<version>[\d+\.]{3}([-\+][\w\.0-9]+)?)"
