name: Create Tag

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # - uses: butlerlogic/action-autotag@stable
    #   with:
    #     GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    #     strategy: package
    #    # root: "/path/to/subdirectory"
    - uses: butlerlogic/action-autotag@1.0.0
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        strategy: regex # Optional since regex_pattern is defined
        root: "src\my.file"
        regex_pattern: "version=([0-9/.])"
