# This is a basic workflow to help you get started with Actions
# run: dotnet test $env:Test_Project_Path --no-restore --logger trx --results-directory "TestResults-${{ matrix.dotnet-version }}"

name: WorkFlow CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
      strategy:
        matrix:
          dotnet-version: [ '3.1.x' ]
          type: [unitarias]
      runs-on: windows-latest
      
      env:
          Solution_Name: src\WebApplicationDGP.sln
          Test_Project_Path: src\TestProject1\TestProject1.csproj       # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.      
          Wap_Project_Path: src\WebApplicationDGP/WebApplicationDGP.csproj                  # Replace with the path to your Wap project, i.e. MyWpf.App.Package\MyWpfApp.Package.wapproj.
          working_directory: src\WebApplicationDGP
          test_result_path: src\TestProject1\TestResults-${{ matrix.dotnet-version }}

          
      steps:
        - uses: actions/checkout@v2
        - name: Setup dotnet
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: '3.1.x'
        - name: Install dependencies
          run: dotnet restore $env:Wap_Project_Path
        - name: Build
          run: dotnet build $env:Wap_Project_Path
        - name: Test with the dotnet CLI
          run: dotnet test $env:Test_Project_Path --no-restore --logger trx --results-directory "TestResults-${{ matrix.dotnet-version }}"
          env:
             Configuration: ${{ matrix.configuration }} 
        #upload test result
        - name: Upload dotnet test results
          uses: actions/upload-artifact@v2
          with:
           name: dotnet-results-${{ matrix.dotnet-version }}
           path: src\TestProject1\TestResults-${{ matrix.dotnet-version }}
              # Use always() to always run this step to publish test results when there are test failures
          if: ${{ always() }}
