#
name: TagGeneration
on:
  push:
    branches:
      - main
jobs:
  TagGenerationjob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: major
      # - name: Create a GitHub release
      #   uses: ncipollo/release-action@v1
      #   with:
      #     tag: ${{ steps.tag_version.outputs.new_tag }}
      #     name: Release ${{ steps.tag_version.outputs.new_tag }}
      #     body: ${{ steps.tag_version.outputs.changelog }}
          
      - name: Set output
        run: |
          echo TAG:
          echo ${{ steps.tag_version.outputs.new_tag }}
          echo RELEASE:
          echo ${{ steps.tag_version.outputs.new_tag }}
          echo BODY:
          echo ${{ steps.tag_version.outputs.changelog }}
          echo "Commit messaje: ${{ github.event.head_commit.message }}

#https://github.com/marketplace/actions/github-tag
