#      patch
name: TagGeneration
on:
  push:
    branches:
      - main
env:
    commit_message: ${{ github.event.head_commit.message }}
    #$commit_pattern: patch
jobs:
  TagGenerationjob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set output
        run: |
          echo TAG:
          echo ${{ steps.tag_version.outputs.new_tag }}
          echo RELEASE:
          echo ${{ steps.tag_version.outputs.new_tag }}
          echo changelog:
          echo ${{ steps.tag_version.outputs.changelog }}
          echo Commit:
          echo ${{ github.event.head_commit.message }}
          echo pull_requesttitle:
          ${{ github.event.pull_request.title }}
          
          
      - name: echo Head Commit message
        run:  echo ${{ github.event.head_commit.message }}
      - name: Find Version Type
        run: echo "commit_pattern=$(echo ${{ github.event.head_commit.message }} | cut -c 2-6)" >> $GITHUB_ENV
      #   id: commit_pattern_id
      #   run: echo "::set-output name=commit_pattern::$(echo ${{ github.event.head_commit.message }} | cut -c 2-6)"
      # - name: Print Version Type
      - name: Print Release Type
        run: echo ${{ env.commit_pattern }}
      #   run: echo ${{ steps.commit_pattern_id.outputs.commit_pattern }}
        
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ env.commit_pattern }}
          #default_bump: ${{ steps.commit_pattern_id.outputs.commit_pattern }}
      # - name: Create a GitHub release
      #   uses: ncipollo/release-action@v1
      #   with:
      #     tag: ${{ steps.tag_version.outputs.new_tag }}
      #     name: Release ${{ steps.tag_version.outputs.new_tag }}
      #     body: ${{ steps.tag_version.outputs.changelog }}
          


#https://github.com/marketplace/actions/github-tag
