trigger: none

pool:
  name: ubuntu-latest


stages:
- stage: StagePipeline
  displayName: Stage from Pipeline
  jobs:
  - job: NuGet
    steps:
    - checkout: self
      clean: true
    - task: NuGetCommand@2
      displayName: NuGet restore
      inputs:
        solution: $(BuildParameters.solution)        
- template: templates/my-stages-template.yaml
