name: AzureLoginSample
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    - run: |
            az webapp list --query "[?state=='Running']"
    
    - name: Sample Azure action
      with: # Set Azure credentials secret as an input
        credentials: ${{ secrets.AZURE_CREDENTIALS }}
      env: # Or as an environment variable
        credentials: ${{ secrets.AZURE_CREDENTIALS }}
    - run: |
            az webapp list --query "[?state=='Running']"   
