#
on: [push]

name: AzurePowerShellSample

jobs:

  build-and-deploy:
    runs-on: windows-latest
    steps:    
    - uses: Azure/login@v1.1
      with:
        creds: '{"clientId":"${{ secrets.ARM_CLIENT_ID }}","clientSecret":"${{ secrets.ARM_CLIENT_SECRET }}","subscriptionId":"${{ secrets.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.ARM_TENANT_ID }}"}'
