# File: .github/workflows/workflow.yml

on: [push]

name: AzurePowerShellLoginSample

jobs:
  build-and-deploy-to-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: actions/checkout@master
            
   # Authentication
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS  }}
    - run: |
        Get-AzVM -ResourceGroupName "ResourceGroup11"
        

